all:  # all files 
  children:  #multiple systems 
    managers:
      hosts:
        swarm-manager:
    workers:
      hosts:
        swarm-worker:
    load_balance:
      hosts:
        nginx2:
  vars:
  ansible_python_interpreter: "/usr/bin/python3"