- hosts: managers
  become: true 
  roles:
  - docker 
  - manager

- hosts: workers
  become: true 
  roles:
  - docker
  - worker

# - hosts: load_balance
#   become: true 
#   roles:
#   - nginx 
 